### ISSUE TITLE
Error in installing the library

### ISSUE THREAD

**Issue by Himscipy** [hippylib/soupy#22]
Hi,
Following the installation instructions results in the following issue. Let me know how to resolve the installation issue. 
```
conda create -n soupy -c conda-forge python=3.11 fenics==2019.1.0 petsc4py==3.19 matplotlib scipy jupyter
Retrieving notices: ...working... done
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - fenics==2019.1.0

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by dc-luo** [comment]
Hi @Himscipy, the installation issue appears to stem from the fact that you're using conda with the arm64 platform, while fenics is only available as an x86 package. Try configuring the environment as an x86 package by putting `CONDA_SUBDIR=osx-64` before the conda call. 

```
CONDA_SUBDIR=osx-64 conda create -n soupy -c conda-forge python=3.11 fenics==2019.1.0 petsc4py==3.19 matplotlib scipy jupyter
```

and then once built, 
```
conda activate soupy
conda config --env --set subdir osx-64
```

This is now in the latest installation instructions. Please let me know if there are further issues.
